# These are supported funding model platforms

github: basava44,raju,rajkumar,vinay
patreon:basava44
open_collective: basava44
ko_fi: basava44
tidelift:html
community_bridge:my kingdom
liberapay: Phonepay
issuehunt: basava44
otechie: basava44
custom: ["1","2","3","4"]
